version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  php:
    build:
      context: .
      target: php
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/wordpress-php}
    image: ${PHP_IMAGE:-d3strukt0r/wordpress-php}
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - wp_content:/app/wp-content
      - ./php/wp-plugin-install.sh:/usr/local/bin/wp-plugin-install
      - ./php/wp-theme-install.sh:/usr/local/bin/wp-theme-install
    environment:
      PHP_MAX_EXECUTION_TIME: 0
      ENVIRONMENT: dev
      DB_PASSWORD: password
      WP_AUTH_KEY: 6dd1921951685a10daf08cc7b400c40dc46434bf
      WP_SECURE_AUTH_KEY: eacb65b6b38b62459c0c0825b3a4a1c135551f0b
      WP_LOGGED_IN_KEY: 8075a1da84d1ea78abe30cdab3d7a627b8d7f671
      WP_NONCE_KEY: 48b769aa02fc87ff62abbdd958cd5696958e147b
      WP_AUTH_SALT: 8e2cfa7959d555733e1914f807ba1f63f19cfe87
      WP_SECURE_AUTH_SALT: add36f5e47fcaead1abbc5b11237af02182a3622
      WP_LOGGED_IN_SALT: 454d11e408fb09abf71fad2ebcfb6c974001ae05
      WP_NONCE_SALT: 33f132e45824f7ed5b580a75d74fce48162847d7

  nginx:
    build:
      context: .
      target: nginx
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/wordpress-php}
        - ${NGINX_IMAGE_CACHE:-d3strukt0r/wordpress-nginx}
    image: ${NGINX_IMAGE:-d3strukt0r/wordpress-nginx}
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
      # - 443:443
    volumes:
      - wp_content:/app/wp-content:ro
    # environment:
    #   USE_HTTPS: "true"

networks:
  internal:
    external: false

volumes:
  database:
  wp_content:
